import { useCallback, useEffect, useState } from 'react'
import { Clock, RefreshCw } from 'lucide-react'
import { formatCurrency } from '../../lib/utils'
import { getErp } from '../../lib/erpApi'

type Pending = { id:string; type:string; ref:string; party:string; date:string; amount:number; status:string; items:number }

export default function Pendings() {
  const [rows, setRows] = useState<Pending[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(() => { setLoading(true); setError(''); Promise.all([getErp<any[]>('orders', undefined, { forceRefresh: true }), getErp<any[]>('challans', undefined, { forceRefresh: true }), getErp<any[]>('sales', undefined, { forceRefresh: true })]).then(([orders, challans, sales]) => { const map = (data:any[], type:string) => (data || []).filter((row:any) => ['pending','draft','partially_received','dispatched'].includes(String(row.status || '').toLowerCase())).map((row:any) => ({ id:String(row.id || row.dbId), type, ref:row.number || row.orderNo || row.id, party:row.party || '', date:row.date || '', amount:Number(row.total || 0), status:row.status || 'pending', items:Number(row.items || (row.lines || []).length) })); setRows([...map(orders, 'Order'), ...map(challans, 'Challan'), ...map(sales, 'Sale')]) }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Pending transactions could not be loaded.')).finally(() => setLoading(false)) }, [])
  useEffect(() => { load() }, [load])
  return <div className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-foreground">Pending Transactions</h1><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><Clock size={14} className="text-amber-600 dark:text-amber-400"/>Live pending orders, challans and sales</p></div><button type="button" onClick={load} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50"><RefreshCw size={16} className={loading ? 'animate-spin' : ''}/>Refresh</button></div>{error && <div role="alert" className="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}<div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="min-w-[46rem] text-xs"><thead><tr><th>Reference</th><th>Type</th><th>Party</th><th>Date</th><th className="text-right">Items</th><th className="text-right">Amount</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">Loading live transactions…</td></tr> : rows.map((row) => <tr key={`${row.type}-${row.id}`}><td className="font-mono">{row.ref}</td><td>{row.type}</td><td>{row.party}</td><td>{row.date}</td><td className="text-right">{row.items}</td><td className="text-right font-mono">{formatCurrency(row.amount)}</td><td className="capitalize text-amber-700 dark:text-amber-400">{row.status}</td></tr>)}{!loading && !error && !rows.length && <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">No pending transactions are recorded.</td></tr>}</tbody></table></div></div>
}
