import { useCallback, useEffect, useState } from 'react'
import { Cloud, Database, RefreshCw } from 'lucide-react'
import { formatCurrency } from '../../lib/utils'
import { getErp } from '../../lib/erpApi'

type RecordRow = { id:string; type:string; ref:string; date:string; amount:number; status:string }
export default function ServerUpload() {
  const [rows, setRows] = useState<RecordRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(() => { setLoading(true); setError(''); Promise.all([getErp<any[]>('sales', undefined, { forceRefresh: true }), getErp<any[]>('purchases', undefined, { forceRefresh: true }), getErp<any[]>('challans', undefined, { forceRefresh: true })]).then(([sales, purchases, challans]) => { const map = (records:any[], type:string) => (records || []).map((row:any) => ({ id:`${type}-${row.id || row.dbId}`, type, ref:row.number || row.id, date:row.date || '', amount:Number(row.total || 0), status:row.status || 'posted' })); setRows([...map(sales, 'Sale'), ...map(purchases, 'Purchase'), ...map(challans, 'Challan')]) }).catch((reason) => setError(reason instanceof Error ? reason.message : 'The live database status could not be loaded.')).finally(() => setLoading(false)) }, [])
  useEffect(() => { load() }, [load])
  const total = rows.reduce((value, row) => value + row.amount, 0)
  return <div className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-foreground">Supabase Sync Status</h1><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><Database size={14} className="text-cyan-600 dark:text-cyan-400"/>Transactions stored in the live ERP database</p></div><button type="button" onClick={load} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50"><RefreshCw size={16} className={loading ? 'animate-spin' : ''}/>Refresh</button></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border bg-card p-4"><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Live records</div><div className="mt-1 text-2xl font-bold text-foreground">{rows.length}</div></div><div className="rounded-xl border border-border bg-card p-4"><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Total value</div><div className="mt-1 text-2xl font-bold text-emerald-600 dark:text-emerald-400">{formatCurrency(total)}</div></div></div>{error && <div role="alert" className="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}<div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="min-w-[40rem] text-xs"><thead><tr><th>Type</th><th>Reference</th><th>Date</th><th className="text-right">Amount</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">Checking Supabase…</td></tr> : rows.map((row) => <tr key={row.id}><td><Cloud size={12} className="mr-2 inline text-cyan-600 dark:text-cyan-400"/>{row.type}</td><td className="font-mono">{row.ref}</td><td>{row.date}</td><td className="text-right font-mono">{formatCurrency(row.amount)}</td><td className="capitalize">{row.status}</td></tr>)}{!loading && !error && !rows.length && <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">No live transaction records are available.</td></tr>}</tbody></table></div></div>
}
