import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, RefreshCw } from 'lucide-react'
import { formatCurrency } from '../../../lib/utils'
import { getErp } from '../../../lib/erpApi'

type Claim = { id:string; claimNo:string; supplier:string; items:number; qty:number; claimed:number; date:string; status:string }
export default function ClaimSettlement() {
  const [rows, setRows] = useState<Claim[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(() => { setLoading(true); setError(''); getErp<any[]>('breakages', undefined, { forceRefresh: true }).then((docs) => setRows((docs || []).map((doc:any) => { const lines = doc.details?.lines || doc.lines || []; return { id:String(doc.id), claimNo:doc.number || doc.document_number || doc.id, supplier:doc.party || doc.details?.supplier || '—', items:lines.length, qty:lines.reduce((total:number, line:any) => total + Number(line.qty || line.quantity || 0), 0), claimed:Number(doc.total || 0), date:doc.date || doc.document_date || '', status:doc.status || 'pending' } }))).catch((reason) => setError(reason instanceof Error ? reason.message : 'Claims could not be loaded.')).finally(() => setLoading(false)) }, [])
  useEffect(() => { load() }, [load])
  const total = rows.reduce((value, row) => value + row.claimed, 0)
  return <div className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-foreground">Claim Settlement</h1><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><AlertTriangle size={14} className="text-amber-600 dark:text-amber-400"/>Live breakage and expiry claims from Supabase</p></div><button type="button" onClick={load} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50"><RefreshCw size={16} className={loading ? 'animate-spin' : ''}/>Refresh</button></div><div className="text-2xl font-mono font-semibold text-amber-700 dark:text-amber-400">{formatCurrency(total)} <span className="text-xs font-sans text-muted-foreground">claim value</span></div>{error && <div role="alert" className="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}<div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="min-w-[46rem] text-xs"><thead><tr><th>Claim</th><th>Supplier</th><th className="text-right">Items</th><th className="text-right">Qty</th><th className="text-right">Claimed</th><th>Date</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">Loading live claims…</td></tr> : rows.map((row) => <tr key={row.id}><td className="font-mono">{row.claimNo}</td><td>{row.supplier}</td><td className="text-right">{row.items}</td><td className="text-right">{row.qty}</td><td className="text-right font-mono">{formatCurrency(row.claimed)}</td><td>{row.date}</td><td className="capitalize text-amber-700 dark:text-amber-400">{row.status}</td></tr>)}{!loading && !error && !rows.length && <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">No breakage or expiry claims are recorded.</td></tr>}</tbody></table></div></div>
}
