import { MasterItemOption } from './medicineMapper'

export interface DistributorProfile {
  name: string
  address: string
  city: string
  phone: string
  email?: string
  gstin: string
  dlNo: string
  stateCode: string
}

export const KNOWN_DISTRIBUTORS: DistributorProfile[] = [
  {
    name: 'REBA PHARMACEUTICALS',
    address: 'C.K. DAS ROAD, NEAR ICICI BANK, TEZPUR-784001',
    city: 'Tezpur',
    phone: '03712355481 / 9854727929',
    email: 'gbjoy2016@gmail.com',
    gstin: '18ANFPG7725A1ZA',
    dlNo: 'D/OL/STR/5608 D/OL/STR/5609',
    stateCode: '18'
  },
  {
    name: 'TIRUPATI PHARMACEUTICALS',
    address: 'N. C. ROAD, TEZPUR, SONITPUR, ASSAM',
    city: 'Tezpur',
    phone: '233072 / 8638389056',
    gstin: '18AGRPD1963G1Z8',
    dlNo: 'STR/4189/90',
    stateCode: '18'
  },
  {
    name: 'AMAR DRUG DISTRIBUTORS',
    address: 'N.C. ROAD, DL. MARKET, TEZPUR, SONITPUR, ASSAM',
    city: 'Tezpur',
    phone: '9854010094 / 03712-314879',
    email: 'ghoshamit92@gmail.com',
    gstin: '18AFWPG3479G1ZV',
    dlNo: 'STR-4337/4338',
    stateCode: '18'
  },
  {
    name: 'MEDICO AGENCY',
    address: 'C.K DAS ROAD, TEZPUR, ASSAM',
    city: 'Tezpur',
    phone: '8638564294 / 6026660558',
    gstin: '18AULPG4107F1ZU',
    dlNo: 'STR-4935/4936',
    stateCode: '18'
  },
  {
    name: 'DRUGS LINE AGENCY',
    address: 'C K DAS ROAD, OPP ICICI BANK, TEZPUR-784001',
    city: 'Tezpur',
    phone: '9394526745 / 9678649155',
    email: 'drugsline.agency@gmail.com',
    gstin: '18AHPB9671M1ZZ',
    dlNo: 'STR-4163/64',
    stateCode: '18'
  }
]

export const MANUFACTURER_CODE_MAP: Record<string, string> = {
  OZONE: 'Ozone Pharmaceuticals Ltd',
  JUPITER: 'Jupiter Remedies',
  TABLET: 'Tablets India Ltd',
  'DR. MORP': 'Dr. Morepen Laboratories',
  'DR MORP': 'Dr. Morepen Laboratories',
  'ALLEN PH': 'Allen Healthcare',
  ALLEN: 'Allen Healthcare',
  HIMALAYA: 'Himalaya Wellness Company',
  NAXPAR: 'Naxpar Pharma',
  MICRO: 'Micro Labs Ltd',
  IPCA: 'Ipca Laboratories',
  STERLI: 'Steril-Gene Life Sciences',
  APEX: 'Apex Laboratories',
  JBCPL: 'J.B. Chemicals & Pharmaceuticals',
  USV: 'USV Private Limited',
  'DRL/ZE': "Dr. Reddy's Laboratories",
  DRL: "Dr. Reddy's Laboratories",
  REE: 'Alembic Pharmaceuticals',
  ALEM: 'Alembic Pharmaceuticals',
  REXWEL: 'Rexwel Pharmaceuticals',
  ALKEM: 'Alkem Laboratories',
  ALKE: 'Alkem Laboratories',
  DYNA: 'Dynamic Techno Medicals',
  LUPI: 'Lupin Limited',
  ABBO: 'Abbott Healthcare',
  SHIN: 'Shin Pharmaceuticals',
  MERC: 'Merck Healthcare',
  INDC: 'Indoco Remedies',
  MACL: 'Macleods Pharmaceuticals'
}

export const PHARMA_MASTER_CATALOG: (MasterItemOption & {
  aliases: string[]
  defaultBatch?: string
  defaultExpiry?: string
})[] = [
  // --- REBA PHARMACEUTICALS ITEMS ---
  {
    id: 'm-reba-01',
    code: 'ITM-DFO-30',
    name: 'D.F.O GEL 30GM',
    label: 'D.F.O GEL 30GM',
    packing: '30GM',
    hsn: '300490',
    mrp: 148.20,
    rate: 112.93,
    purchaseRate: 112.93,
    gstRate: 5,
    stock: 240,
    manufacturer: 'Ozone Pharmaceuticals Ltd',
    salt: 'Diclofenac Diethylamine, Linseed Oil, Methyl Salicylate, Menthol',
    category: 'Topical Pain Relief',
    aliases: ['D.F.O GEL', 'DFO GEL', 'DFO GEL 30GM', 'D.F.O GEL 30G', 'DFO PAIN GEL']
  },
  {
    id: 'm-reba-02',
    code: 'ITM-CARM-250',
    name: 'CARMINOZYME LIQ',
    label: 'CARMINOZYME LIQ 250ML',
    packing: '250ML',
    hsn: '300490',
    mrp: 159.38,
    rate: 121.44,
    purchaseRate: 121.44,
    gstRate: 5,
    stock: 180,
    manufacturer: 'Jupiter Remedies',
    salt: 'Digestive Enzymes, Fungal Diastase, Pepsin',
    category: 'Digestive Aid',
    aliases: ['CARMINOZYME LIQ', 'CARMINOZYME', 'CARMINOZYME LIQUID', 'CARMINOZYME 250ML', 'CARMINOZYME SYRUP']
  },
  {
    id: 'm-reba-03',
    code: 'ITM-BIFI-10',
    name: 'BIFILAC CAP',
    label: 'BIFILAC CAP',
    packing: "10'S",
    hsn: '300290',
    mrp: 149.00,
    rate: 113.52,
    purchaseRate: 113.52,
    gstRate: 5,
    stock: 350,
    manufacturer: 'Tablets India Ltd',
    salt: 'Streptococcus Faecalis, Clostridium Butyricum, Bacillus Mesentericus, Lactic Acid Bacillus',
    category: 'Probiotic',
    aliases: ['BIFILAC CAP', 'BIFILAC', 'BIFILAC CAPSULE', 'BIFILAC CAPSULES', 'BIFILAC 10S']
  },
  {
    id: 'm-reba-04',
    code: 'ITM-BURN-10',
    name: 'BURNOL CREAM',
    label: 'BURNOL CREAM 10GM',
    packing: '10GM',
    hsn: '300490',
    mrp: 85.00,
    rate: 67.83,
    purchaseRate: 67.83,
    gstRate: 5,
    stock: 400,
    manufacturer: 'Dr. Morepen Laboratories',
    salt: 'Aminacrine HCL, Cetrimide',
    category: 'Antiseptic Cream',
    aliases: ['BURNOL CREAM', 'BURNOL', 'BURNOL 10GM', 'BURNOL ANTISEPTIC', 'BURNOL OINTMENT']
  },
  {
    id: 'm-reba-05',
    code: 'ITM-LIVO-200',
    name: 'LIVOSIN SYP 200 M',
    label: 'LIVOSIN SYP 200ML',
    packing: '200ML',
    hsn: '330720',
    mrp: 175.00,
    rate: 130.55,
    purchaseRate: 130.55,
    gstRate: 5,
    stock: 190,
    manufacturer: 'Allen Healthcare',
    salt: 'Ayurvedic Liver Tonic Formulation',
    category: 'Ayurvedic Tonic',
    aliases: ['LIVOSIN SYP 200 M', 'LIVOSIN SYP 200ML', 'LIVOSIN SYRUP', 'LIVOSIN', 'LIVOSIN 200ML']
  },
  {
    id: 'm-reba-06',
    code: 'ITM-CYST-60',
    name: 'CYSTONE TAB',
    label: 'CYSTONE TAB',
    packing: "60'S",
    hsn: '330720',
    mrp: 260.00,
    rate: 185.72,
    purchaseRate: 185.72,
    gstRate: 5,
    stock: 300,
    manufacturer: 'Himalaya Wellness Company',
    salt: 'Didymocarpus Pedicellata, Saxifraga Ligulata',
    category: 'Renal Care',
    aliases: ['CYSTONE TAB', 'CYSTONE', 'CYSTONE TABLET', 'CYSTONE 60S', 'HIMALAYA CYSTONE']
  },

  // --- TIRUPATI PHARMACEUTICALS ITEMS ---
  {
    id: 'm-tiru-01',
    code: 'ITM-DOLO-DROP',
    name: 'DOLO DROP',
    label: 'DOLO DROP 15ML',
    packing: '15ML',
    hsn: '300490',
    mrp: 30.90,
    rate: 23.54,
    purchaseRate: 23.54,
    gstRate: 5,
    stock: 550,
    manufacturer: 'Micro Labs Ltd',
    salt: 'Paracetamol Paediatric Drops 100mg/ml',
    category: 'Paediatric Antipyretic',
    aliases: ['DOLO DROP', 'DOLO DROPS', 'DOLO 15ML DROPS', 'DOLO PAEDIATRIC DROP', 'DOLO DROP 15ML']
  },
  {
    id: 'm-tiru-02',
    code: 'ITM-DOLO-650',
    name: 'DOLO-650 TAB',
    label: 'DOLO-650 TAB',
    packing: '15S',
    hsn: '300490',
    mrp: 32.12,
    rate: 24.47,
    purchaseRate: 24.47,
    gstRate: 5,
    stock: 1200,
    manufacturer: 'Micro Labs Ltd',
    salt: 'Paracetamol 650mg',
    category: 'Analgesic / Antipyretic',
    aliases: ['DOLO-650 TAB', 'DOLO-650', 'DOLO 650', 'DOLO 650 TAB', 'DOLO 650MG', 'DOLO 650 TABLET']
  },
  {
    id: 'm-tiru-03',
    code: 'ITM-ZERO-SP',
    name: 'ZERODOL SP TAB',
    label: 'ZERODOL SP TAB',
    packing: '10S',
    hsn: '300490',
    mrp: 139.69,
    rate: 106.42,
    purchaseRate: 106.42,
    gstRate: 5,
    stock: 800,
    manufacturer: 'Ipca Laboratories',
    salt: 'Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg',
    category: 'Pain Relief / Anti-inflammatory',
    aliases: ['ZERODOL SP TAB', 'ZERODOL SP', 'ZERODOL-SP', 'ZERODOL SP 10S', 'ZERODOL SP TABLET']
  },
  {
    id: 'm-tiru-04',
    code: 'ITM-DOLO-120',
    name: 'DOLO-120 SUSP',
    label: 'DOLO-120 SUSP 60ML',
    packing: '60ML',
    hsn: '300490',
    mrp: 39.06,
    rate: 29.76,
    purchaseRate: 29.76,
    gstRate: 5,
    stock: 450,
    manufacturer: 'Micro Labs Ltd',
    salt: 'Paracetamol Paediatric Suspension 120mg/5ml',
    category: 'Paediatric Suspension',
    aliases: ['DOLO-120 SUSP', 'DOLO 120 SUSP', 'DOLO 120 SUSPENSION', 'DOLO-120', 'DOLO 120 SYRUP']
  },
  {
    id: 'm-tiru-05',
    code: 'ITM-DOLO-250',
    name: 'DOLO-250 SUSP',
    label: 'DOLO-250 SUSP 60ML',
    packing: '60ML',
    hsn: '300490',
    mrp: 42.84,
    rate: 32.64,
    purchaseRate: 32.64,
    gstRate: 5,
    stock: 650,
    manufacturer: 'Micro Labs Ltd',
    salt: 'Paracetamol Paediatric Suspension 250mg/5ml',
    category: 'Paediatric Suspension',
    aliases: ['DOLO-250 SUSP', 'DOLO 250 SUSP', 'DOLO 250 SUSPENSION', 'DOLO-250', 'DOLO 250 SYRUP']
  },

  // --- AMAR DRUG DISTRIBUTORS ITEMS ---
  {
    id: 'm-amar-01',
    code: 'ITM-ZINC-SYP',
    name: 'ZINCOVIT SYP',
    label: 'ZINCOVIT SYP 200ML',
    packing: '200ML',
    hsn: '21069099',
    mrp: 160.17,
    rate: 122.03,
    purchaseRate: 122.03,
    gstRate: 5,
    stock: 500,
    manufacturer: 'Apex Laboratories',
    salt: 'Multivitamin, Multimineral with Zinc Drops/Syrup',
    category: 'Nutritional Supplement',
    aliases: ['ZINCOVIT SYP', 'ZINCOVIT SYRUP', 'ZINCOVIT 200ML', 'ZINCOVIT', 'ZINCOVIT SYRUP 200ML']
  },
  {
    id: 'm-amar-02',
    code: 'ITM-NICA-20',
    name: 'NICARDIA RTD20(30TAB)',
    label: 'NICARDIA RTD 20 TAB',
    packing: "30'S",
    hsn: '30049062',
    mrp: 159.64,
    rate: 121.63,
    purchaseRate: 121.63,
    gstRate: 5,
    stock: 320,
    manufacturer: 'J.B. Chemicals & Pharmaceuticals',
    salt: 'Nifedipine Retard 20mg',
    category: 'Antihypertensive',
    aliases: ['NICARDIA RTD20(30TAB)', 'NICARDIA RTD 20', 'NICARDIA RTD20', 'NICARDIA RETARD 20', 'NICARDIA RTD']
  },
  {
    id: 'm-amar-03',
    code: 'ITM-ECOS-75-20',
    name: 'ECOSPRIN AV75/20',
    label: 'ECOSPRIN AV 75/20 CAP',
    packing: '15CAP',
    hsn: '30049062',
    mrp: 66.80,
    rate: 53.44,
    purchaseRate: 53.44,
    gstRate: 5,
    stock: 450,
    manufacturer: 'USV Private Limited',
    salt: 'Aspirin 75mg + Atorvastatin 20mg',
    category: 'Cardiovascular',
    aliases: ['ECOSPRIN AV75/20', 'ECOSPRIN AV 75/20', 'ECOSPRIN AV 75 20', 'ECOSPRIN AV75 20', 'ECOSPRIN AV']
  },
  {
    id: 'm-amar-04',
    code: 'ITM-KEPP-500',
    name: 'KEPPRA-500(14S)',
    label: 'KEPPRA 500 TAB',
    packing: '14TAB',
    hsn: '30049082',
    mrp: 194.01,
    rate: 147.82,
    purchaseRate: 147.82,
    gstRate: 5,
    stock: 220,
    manufacturer: "Dr. Reddy's Laboratories",
    salt: 'Levetiracetam 500mg',
    category: 'Antiepileptic',
    aliases: ['KEPPRA-500(14S)', 'KEPPRA-500', 'KEPPRA 500', 'KEPPRA 500MG', 'KEPPRA 500 TAB']
  },
  {
    id: 'm-amar-05',
    code: 'ITM-STAM-25',
    name: 'STAMLO 2.5MG 30TAB',
    label: 'STAMLO 2.5MG TAB',
    packing: '30S',
    hsn: '30049072',
    mrp: 57.64,
    rate: 43.92,
    purchaseRate: 43.92,
    gstRate: 5,
    stock: 310,
    manufacturer: "Dr. Reddy's Laboratories",
    salt: 'Amlodipine 2.5mg',
    category: 'Antihypertensive',
    aliases: ['STAMLO 2.5MG 30TAB', 'STAMLO 2.5MG', 'STAMLO 2.5', 'STAMLO 2.5 TAB', 'STAMLO 2.5MG TABLET']
  },
  {
    id: 'm-amar-06',
    code: 'ITM-RANT-SYP',
    name: 'RANTAC SYRUP',
    label: 'RANTAC SYRUP 100ML',
    packing: '100ML',
    hsn: '30049033',
    mrp: 183.23,
    rate: 139.61,
    purchaseRate: 139.61,
    gstRate: 5,
    stock: 380,
    manufacturer: 'J.B. Chemicals & Pharmaceuticals',
    salt: 'Ranitidine Hydrochloride Syrup 75mg/5ml',
    category: 'Antacid / Antiulcer',
    aliases: ['RANTAC SYRUP', 'RANTAC SYP', 'RANTAC 100ML', 'RANTAC SYRUP 100ML', 'RANTAC']
  },
  {
    id: 'm-amar-07',
    code: 'ITM-METR-400',
    name: 'METROGYL IP 400',
    label: 'METROGYL 400 TAB',
    packing: '20 TAB',
    hsn: '30049022',
    mrp: 32.76,
    rate: 26.90,
    purchaseRate: 26.90,
    gstRate: 5,
    stock: 750,
    manufacturer: 'J.B. Chemicals & Pharmaceuticals',
    salt: 'Metronidazole 400mg',
    category: 'Antiprotozoal / Antibiotic',
    aliases: ['METROGYL IP 400', 'METROGYL 400', 'METROGYL 400MG', 'METROGYL 400 TAB', 'METROGYL IP 400 TAB']
  },
  {
    id: 'm-amar-08',
    code: 'ITM-METR-SYP',
    name: 'METROGYL SYP',
    label: 'METROGYL SYRUP 100ML',
    packing: '100ML',
    hsn: '30049022',
    mrp: 55.43,
    rate: 45.52,
    purchaseRate: 45.52,
    gstRate: 5,
    stock: 290,
    manufacturer: 'J.B. Chemicals & Pharmaceuticals',
    salt: 'Metronidazole Benzoate 200mg/5ml',
    category: 'Antiprotozoal Suspension',
    aliases: ['METROGYL SYP', 'METROGYL SYRUP', 'METROGYL SUSP', 'METROGYL 100ML', 'METROGYL SUSPENSION']
  },
  {
    id: 'm-amar-09',
    code: 'ITM-DERO-30',
    name: 'DEROBIN OINT',
    label: 'DEROBIN OINT 30GM',
    packing: '30GM',
    hsn: '30049099',
    mrp: 130.78,
    rate: 99.64,
    purchaseRate: 99.64,
    gstRate: 5,
    stock: 210,
    manufacturer: 'USV Private Limited',
    salt: 'Dithranol, Salicylic Acid, Coal Tar',
    category: 'Antipsoriatic',
    aliases: ['DEROBIN OINT', 'DEROBIN', 'DEROBIN OINTMENT', 'DEROBIN 30GM', 'DEROBIN CREAM']
  },
  {
    id: 'm-amar-10',
    code: 'ITM-TAZL-40',
    name: 'TAZLOC-40(10*15)',
    label: 'TAZLOC 40 TAB',
    packing: '15TAB',
    hsn: '30049089',
    mrp: 97.25,
    rate: 74.10,
    purchaseRate: 74.10,
    gstRate: 5,
    stock: 420,
    manufacturer: 'USV Private Limited',
    salt: 'Telmisartan 40mg',
    category: 'Antihypertensive',
    aliases: ['TAZLOC-40(10*15)', 'TAZLOC-40', 'TAZLOC 40', 'TAZLOC 40MG', 'TAZLOC 40 TAB']
  },

  // --- MEDICO AGENCY ITEMS ---
  {
    id: 'm-med-01',
    code: 'ITM-PENT-40',
    name: 'PENTAB 40 TAB',
    label: 'PENTAB 40 TAB',
    packing: "10'S",
    hsn: '3004',
    mrp: 168.09,
    rate: 38.50,
    purchaseRate: 38.50,
    gstRate: 5,
    stock: 500,
    manufacturer: 'Alembic Pharmaceuticals',
    salt: 'Pantoprazole Gastro-Resistant 40mg',
    category: 'Proton Pump Inhibitor',
    aliases: ['PENTAB 40 TAB', 'PENTAB 40', 'PENTAB 40MG', 'PENTAB 40 TABLET', 'PENTAB']
  },
  {
    id: 'm-med-02',
    code: 'ITM-PENT-DSR',
    name: 'PENTAB-DSR CAP',
    label: 'PENTAB-DSR CAP',
    packing: "10'S",
    hsn: '3004',
    mrp: 145.21,
    rate: 38.50,
    purchaseRate: 38.50,
    gstRate: 5,
    stock: 480,
    manufacturer: 'Alembic Pharmaceuticals',
    salt: 'Pantoprazole 40mg + Domperidone SR 30mg',
    category: 'Antacid / Antiemetic',
    aliases: ['PENTAB-DSR CAP', 'PENTAB DSR', 'PENTAB-DSR', 'PENTAB DSR CAP', 'PENTAB DSR CAPSULE']
  },
  {
    id: 'm-med-03',
    code: 'ITM-PEKT-TAB',
    name: 'PEKTIN TAB',
    label: 'PEKTIN TAB',
    packing: '1ST',
    hsn: '3401',
    mrp: 25.00,
    rate: 2.00,
    purchaseRate: 2.00,
    gstRate: 18,
    stock: 800,
    manufacturer: 'Rexwel Pharmaceuticals',
    salt: 'Permethrin / Medicated Soap Formulation',
    category: 'Medicated Soap',
    aliases: ['PEKTIN TAB', 'PEKTIN', 'PEKTIN TABLET', 'PEKTIN SOAP', 'PEKTIN 1ST']
  },
  {
    id: 'm-med-04',
    code: 'ITM-KETO-SOAP',
    name: 'KETOKEM SOAP',
    label: 'KETOKEM SOAP 75GM',
    packing: '75GM',
    hsn: '3004',
    mrp: 160.00,
    rate: 44.80,
    purchaseRate: 44.80,
    gstRate: 5,
    stock: 260,
    manufacturer: 'Alkem Laboratories',
    salt: 'Ketoconazole 2% Soap',
    category: 'Antifungal Soap',
    aliases: ['KETOKEM SOAP', 'KETOKEM 75GM', 'KETOKEM', 'KETOKEM ANTI DANDRUFF', 'KETOKEM SOAP 75G']
  },
  {
    id: 'm-med-05',
    code: 'ITM-SENG-CAP',
    name: 'SENGVITAL CAP',
    label: 'SENGVITAL CAP',
    packing: "10'S",
    hsn: '3004',
    mrp: 134.05,
    rate: 19.78,
    purchaseRate: 19.78,
    gstRate: 5,
    stock: 310,
    manufacturer: 'Alkem Laboratories',
    salt: 'Ginseng with Multivitamins and Minerals',
    category: 'Nutritional Supplement',
    aliases: ['SENGVITAL CAP', 'SENGVITAL', 'SENGVITAL CAPSULE', 'SENGVITAL CAPSULES', 'SENGVITAL 10S']
  },
  {
    id: 'm-med-06',
    code: 'ITM-RABA-DSR',
    name: 'RABALKEM DSR CAP',
    label: 'RABALKEM DSR CAP',
    packing: "10'S",
    hsn: '3004',
    mrp: 145.30,
    rate: 17.00,
    purchaseRate: 17.00,
    gstRate: 5,
    stock: 340,
    manufacturer: 'Alkem Laboratories',
    salt: 'Rabeprazole 20mg + Domperidone SR 30mg',
    category: 'Proton Pump Inhibitor',
    aliases: ['RABALKEM DSR CAP', 'RABALKEM DSR', 'RABALKEM-DSR', 'RABALKEM DSR 10S', 'RABALKEM DSR CAPSULE']
  },
  {
    id: 'm-med-07',
    code: 'ITM-MICR-200',
    name: 'MICROPOD 200MG TAB',
    label: 'MICROPOD 200MG TAB',
    packing: "10'S",
    hsn: '3004',
    mrp: 259.30,
    rate: 66.50,
    purchaseRate: 66.50,
    gstRate: 5,
    stock: 220,
    manufacturer: 'Micro Labs Ltd',
    salt: 'Cefpodoxime Proxetil 200mg',
    category: 'Cephalosporin Antibiotic',
    aliases: ['MICROPOD 200MG TAB', 'MICROPOD 200', 'MICROPOD 200MG', 'MICROPOD 200 TAB', 'MICROPOD']
  },
  {
    id: 'm-med-08',
    code: 'ITM-BREA-PUMP',
    name: 'BREAST PUMP',
    label: 'BREAST PUMP',
    packing: '1pcs',
    hsn: '9018',
    mrp: 91.87,
    rate: 50.00,
    purchaseRate: 50.00,
    gstRate: 5,
    stock: 90,
    manufacturer: 'Lupin Limited',
    salt: 'Medical Surgical Device',
    category: 'Surgicals & Devices',
    aliases: ['BREAST PUMP', 'BREAST PUMP MANUAL', 'LUPIN BREAST PUMP', 'MANUAL BREAST PUMP']
  },
  {
    id: 'm-med-09',
    code: 'ITM-LS-BELT',
    name: 'L S BELT L (DYNA)',
    label: 'L S BELT L (DYNA)',
    packing: '1PCS',
    hsn: '9021',
    mrp: 1050.00,
    rate: 546.00,
    purchaseRate: 546.00,
    gstRate: 5,
    stock: 65,
    manufacturer: 'Dynamic Techno Medicals',
    salt: 'Lumbo Sacral Support Device',
    category: 'Orthopaedic Supports',
    aliases: ['L S BELT L (DYNA)', 'L S BELT', 'LS BELT', 'LUMBO SACRAL BELT', 'L S BELT LARGE', 'LS BELT DYNA']
  },

  // --- DRUGS LINE AGENCY ITEMS ---
  {
    id: 'm-drug-01',
    code: 'ITM-RABL-D',
    name: 'RABLET D CAP.',
    label: 'RABLET D CAP.',
    packing: '10 S',
    hsn: '300490',
    mrp: 312.00,
    rate: 237.71,
    purchaseRate: 237.71,
    gstRate: 5,
    stock: 290,
    manufacturer: 'Lupin Limited',
    salt: 'Rabeprazole Sodium 20mg + Domperidone 30mg',
    category: 'Proton Pump Inhibitor',
    aliases: ['RABLET D CAP.', 'RABLET D CAP', 'RABLET D', 'RABLET-D', 'RABLET D 10S', 'RABLET D CAPSULE']
  },
  {
    id: 'm-drug-02',
    code: 'ITM-VERT-16',
    name: 'VERTIN 16 TAB',
    label: 'VERTIN 16 TAB',
    packing: '15 S',
    hsn: '300490',
    mrp: 405.94,
    rate: 309.29,
    purchaseRate: 309.29,
    gstRate: 5,
    stock: 310,
    manufacturer: 'Abbott Healthcare',
    salt: 'Betahistine Dihydrochloride 16mg',
    category: 'Antivertigo',
    aliases: ['VERTIN 16 TAB', 'VERTIN 16', 'VERTIN 16MG', 'VERTIN 16 TABLET', 'VERTIN 16MG TAB']
  },
  {
    id: 'm-drug-03',
    code: 'ITM-S-VOCT',
    name: 'S VOCTA 10TAB',
    label: 'S VOCTA 10TAB',
    packing: '10TAB',
    hsn: '300490',
    mrp: 141.28,
    rate: 107.65,
    purchaseRate: 107.65,
    gstRate: 5,
    stock: 210,
    manufacturer: 'Shin Pharmaceuticals',
    salt: 'Voglibose 0.2mg',
    category: 'Antidiabetic',
    aliases: ['S VOCTA 10TAB', 'S VOCTA', 'S VOCTA 10', 'S-VOCTA 10', 'S VOCTA TABLET']
  },
  {
    id: 'm-drug-04',
    code: 'ITM-CONC-125',
    name: 'CONCOR COR 1.25',
    label: 'CONCOR COR 1.25 TAB',
    packing: '10s',
    hsn: '300490',
    mrp: 79.53,
    rate: 60.60,
    purchaseRate: 60.60,
    gstRate: 5,
    stock: 250,
    manufacturer: 'Merck Healthcare',
    salt: 'Bisoprolol Fumarate 1.25mg',
    category: 'Cardiovascular / Beta Blocker',
    aliases: ['CONCOR COR 1.25', 'CONCOR COR 1.25MG', 'CONCOR COR', 'CONCOR 1.25', 'CONCOR COR TAB']
  },
  {
    id: 'm-drug-05',
    code: 'ITM-XONE-1125',
    name: 'XONE XP 1.125GM',
    label: 'XONE XP 1.125GM INJ',
    packing: '1 VIAL',
    hsn: '300420',
    mrp: 261.90,
    rate: 199.54,
    purchaseRate: 199.54,
    gstRate: 5,
    stock: 400,
    manufacturer: 'Alkem Laboratories',
    salt: 'Ceftriaxone 1000mg + Tazobactam 125mg',
    category: 'Injectable Antibiotic',
    aliases: ['XONE XP 1.125GM', 'XONE XP 1.125', 'XONE XP', 'XONE XP INJ', 'XONE XP INJECTION']
  },
  {
    id: 'm-drug-06',
    code: 'ITM-T-HEAL',
    name: 'T-HEAL CAP',
    label: 'T-HEAL CAP',
    packing: '10 S',
    hsn: '210690',
    mrp: 480.55,
    rate: 366.14,
    purchaseRate: 366.14,
    gstRate: 5,
    stock: 180,
    manufacturer: 'Alkem Laboratories',
    salt: 'Mucopolysaccharide, Collagen Peptide Type I, Sodium Hyaluronate',
    category: 'Joint Health',
    aliases: ['T-HEAL CAP', 'T-HEAL', 'T HEAL CAP', 'THEAL CAP', 'T-HEAL CAPSULE']
  },
  {
    id: 'm-drug-07',
    code: 'ITM-PAN-40',
    name: 'PAN 40MG TAB',
    label: 'PAN 40MG TAB',
    packing: '15 S',
    hsn: '300490',
    mrp: 192.80,
    rate: 146.90,
    purchaseRate: 146.90,
    gstRate: 5,
    stock: 950,
    manufacturer: 'Alkem Laboratories',
    salt: 'Pantoprazole Gastro-Resistant 40mg',
    category: 'Proton Pump Inhibitor',
    aliases: ['PAN 40MG TAB', 'PAN 40', 'PAN 40MG', 'PAN-40 TAB', 'PAN 40 TAB', 'PAN 40MG TABLET']
  },
  {
    id: 'm-drug-08',
    code: 'ITM-ZECA-GOLD',
    name: 'ZECAL GOLD TAB',
    label: 'ZECAL GOLD TAB',
    packing: '1x30ca',
    hsn: '300450',
    mrp: 445.31,
    rate: 339.29,
    purchaseRate: 339.29,
    gstRate: 5,
    stock: 280,
    manufacturer: 'Indoco Remedies',
    salt: 'Calcitriol, Calcium Carbonate, Zinc, Magnesium, Vitamin K2-7',
    category: 'Calcium / Bone Health',
    aliases: ['ZECAL GOLD TAB', 'ZECAL GOLD', 'ZECAL-GOLD', 'ZECAL GOLD 30S', 'ZECAL GOLD TABLET']
  },
  {
    id: 'm-drug-09',
    code: 'ITM-GEMI-M1',
    name: 'GEMINOR M1',
    label: 'GEMINOR M1 TAB',
    packing: '15S',
    hsn: '300490',
    mrp: 167.05,
    rate: 127.28,
    purchaseRate: 127.28,
    gstRate: 5,
    stock: 510,
    manufacturer: 'Macleods Pharmaceuticals',
    salt: 'Glimepiride 1mg + Metformin Hydrochloride 500mg SR',
    category: 'Oral Antidiabetic',
    aliases: ['GEMINOR M1', 'GEMINOR M1 TAB', 'GEMINOR-M1', 'GEMINOR M 1', 'GEMINOR M1 TABLET']
  },
  {
    id: 'm-drug-10',
    code: 'ITM-GEMI-M2',
    name: 'GEMINOR M2',
    label: 'GEMINOR M2 TAB',
    packing: '15S',
    hsn: '300490',
    mrp: 231.81,
    rate: 176.62,
    purchaseRate: 176.62,
    gstRate: 5,
    stock: 490,
    manufacturer: 'Macleods Pharmaceuticals',
    salt: 'Glimepiride 2mg + Metformin Hydrochloride 500mg SR',
    category: 'Oral Antidiabetic',
    aliases: ['GEMINOR M2', 'GEMINOR M2 TAB', 'GEMINOR-M2', 'GEMINOR M 2', 'GEMINOR M2 TABLET']
  },
  {
    id: 'm-drug-11',
    code: 'ITM-GEMI-M4',
    name: 'GEMINOR M4 FORTE',
    label: 'GEMINOR M4 FORTE TAB',
    packing: '15S',
    hsn: '300490',
    mrp: 262.97,
    rate: 200.37,
    purchaseRate: 200.37,
    gstRate: 5,
    stock: 330,
    manufacturer: 'Macleods Pharmaceuticals',
    salt: 'Glimepiride 4mg + Metformin Hydrochloride 1000mg SR',
    category: 'Oral Antidiabetic',
    aliases: ['GEMINOR M4 FORTE', 'GEMINOR M4 FORTE TAB', 'GEMINOR-M4 FORTE', 'GEMINOR M4', 'GEMINOR M4 TABLET']
  },
  {
    id: 'm-drug-12',
    code: 'ITM-ZECA-ACT',
    name: 'ZECAL ACTIVE',
    label: 'ZECAL ACTIVE TAB',
    packing: '30S',
    hsn: '300450',
    mrp: 536.00,
    rate: 408.38,
    purchaseRate: 408.38,
    gstRate: 5,
    stock: 190,
    manufacturer: 'Indoco Remedies',
    salt: 'Calcium Citrate Malate, Vitamin D3, Folic Acid',
    category: 'Calcium / Bone Health',
    aliases: ['ZECAL ACTIVE', 'ZECAL ACTIVE TAB', 'ZECAL-ACTIVE', 'ZECAL ACTIVE 30S', 'ZECAL ACTIVE TABLET']
  }
]
