-- PharmaERP initial PostgreSQL schema. Apply with a privileged migration role.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE party_type AS ENUM ('customer','supplier','both');
CREATE TYPE document_status AS ENUM ('draft','posted','cancelled','completed');
CREATE TYPE movement_type AS ENUM ('opening','purchase','sale','sale_return','purchase_return','transfer_in','transfer_out','adjustment','expiry','breakage');
CREATE TYPE voucher_type AS ENUM ('receipt','payment','journal','contra','debit_note','credit_note','sale','purchase');

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, gstin text UNIQUE, base_currency text NOT NULL DEFAULT 'INR', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, name text NOT NULL, UNIQUE (organization_id, code));
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), role_id uuid REFERENCES roles(id), email text NOT NULL, password_hash text NOT NULL, display_name text NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, email));
CREATE TABLE financial_years (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), starts_on date NOT NULL, ends_on date NOT NULL, is_closed boolean NOT NULL DEFAULT false, UNIQUE (organization_id, starts_on));

CREATE TABLE parties (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, party_type party_type NOT NULL, legal_name text NOT NULL, phone text, email text, gstin text, credit_limit numeric(14,2) NOT NULL DEFAULT 0, is_blocked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, code));
CREATE TABLE party_addresses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), party_id uuid NOT NULL REFERENCES parties(id) ON DELETE CASCADE, address_type text NOT NULL, line1 text NOT NULL, city text, state_code text, postal_code text, is_default boolean NOT NULL DEFAULT false);
CREATE TABLE manufacturers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, UNIQUE (organization_id, name));
CREATE TABLE salts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, UNIQUE (organization_id, name));
CREATE TABLE hsn_codes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, description text, gst_rate numeric(5,2) NOT NULL DEFAULT 0, UNIQUE (organization_id, code));
CREATE TABLE items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, name text NOT NULL, manufacturer_id uuid REFERENCES manufacturers(id), salt_id uuid REFERENCES salts(id), hsn_id uuid REFERENCES hsn_codes(id), packing text, mrp numeric(14,2) NOT NULL DEFAULT 0, sale_rate numeric(14,2) NOT NULL DEFAULT 0, purchase_rate numeric(14,2) NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, UNIQUE (organization_id, code));
CREATE TABLE warehouses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, name text NOT NULL, UNIQUE (organization_id, code));
CREATE TABLE item_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), item_id uuid NOT NULL REFERENCES items(id), batch_number text NOT NULL, expiry_on date, mrp numeric(14,2) NOT NULL DEFAULT 0, UNIQUE (item_id, batch_number));
CREATE TABLE stock_movements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), item_batch_id uuid NOT NULL REFERENCES item_batches(id), warehouse_id uuid NOT NULL REFERENCES warehouses(id), movement_type movement_type NOT NULL, quantity numeric(14,3) NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), source_type text, source_id uuid, remarks text);

CREATE TABLE chart_of_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, name text NOT NULL, account_type text NOT NULL, parent_id uuid REFERENCES chart_of_accounts(id), party_id uuid UNIQUE REFERENCES parties(id), is_active boolean NOT NULL DEFAULT true, UNIQUE (organization_id, code));
CREATE TABLE vouchers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), financial_year_id uuid NOT NULL REFERENCES financial_years(id), voucher_type voucher_type NOT NULL, voucher_number text NOT NULL, voucher_date date NOT NULL, status document_status NOT NULL DEFAULT 'draft', narration text, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, financial_year_id, voucher_number));
CREATE TABLE voucher_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), voucher_id uuid NOT NULL REFERENCES vouchers(id) ON DELETE CASCADE, account_id uuid NOT NULL REFERENCES chart_of_accounts(id), debit numeric(14,2) NOT NULL DEFAULT 0 CHECK (debit >= 0), credit numeric(14,2) NOT NULL DEFAULT 0 CHECK (credit >= 0), narration text, CHECK ((debit = 0) <> (credit = 0)));

CREATE TABLE sales_invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), financial_year_id uuid NOT NULL REFERENCES financial_years(id), party_id uuid NOT NULL REFERENCES parties(id), invoice_number text NOT NULL, invoice_date date NOT NULL, status document_status NOT NULL DEFAULT 'draft', subtotal numeric(14,2) NOT NULL DEFAULT 0, discount_total numeric(14,2) NOT NULL DEFAULT 0, tax_total numeric(14,2) NOT NULL DEFAULT 0, grand_total numeric(14,2) NOT NULL DEFAULT 0, voucher_id uuid UNIQUE REFERENCES vouchers(id), UNIQUE (organization_id, financial_year_id, invoice_number));
CREATE TABLE sales_invoice_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id uuid NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE, item_id uuid NOT NULL REFERENCES items(id), item_batch_id uuid REFERENCES item_batches(id), quantity numeric(14,3) NOT NULL CHECK (quantity > 0), free_quantity numeric(14,3) NOT NULL DEFAULT 0, rate numeric(14,2) NOT NULL, discount_percent numeric(5,2) NOT NULL DEFAULT 0, gst_rate numeric(5,2) NOT NULL DEFAULT 0, line_total numeric(14,2) NOT NULL);
CREATE TABLE delivery_challans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), financial_year_id uuid NOT NULL REFERENCES financial_years(id), party_id uuid NOT NULL REFERENCES parties(id), challan_number text NOT NULL, challan_date date NOT NULL, transport_name text, status document_status NOT NULL DEFAULT 'draft', invoice_id uuid REFERENCES sales_invoices(id), UNIQUE (organization_id, financial_year_id, challan_number));
CREATE TABLE delivery_challan_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), challan_id uuid NOT NULL REFERENCES delivery_challans(id) ON DELETE CASCADE, item_batch_id uuid NOT NULL REFERENCES item_batches(id), quantity numeric(14,3) NOT NULL CHECK (quantity > 0));
CREATE TABLE receipts_payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), party_id uuid REFERENCES parties(id), voucher_id uuid NOT NULL UNIQUE REFERENCES vouchers(id), payment_mode text NOT NULL, amount numeric(14,2) NOT NULL CHECK (amount > 0), reference_number text, received_on date NOT NULL);
CREATE TABLE gst_returns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), financial_year_id uuid NOT NULL REFERENCES financial_years(id), return_type text NOT NULL, period_start date NOT NULL, period_end date NOT NULL, status document_status NOT NULL DEFAULT 'draft', UNIQUE (organization_id, return_type, period_start));
CREATE TABLE audit_logs (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid REFERENCES users(id), entity_type text NOT NULL, entity_id uuid NOT NULL, action text NOT NULL, before_state jsonb, after_state jsonb, occurred_at timestamptz NOT NULL DEFAULT now());

CREATE INDEX idx_parties_org_name ON parties (organization_id, legal_name);
CREATE INDEX idx_items_org_name ON items (organization_id, name);
CREATE INDEX idx_stock_batch_warehouse ON stock_movements (item_batch_id, warehouse_id, occurred_at DESC);
CREATE INDEX idx_voucher_lines_account ON voucher_lines (account_id, voucher_id);
CREATE INDEX idx_sales_party_date ON sales_invoices (party_id, invoice_date DESC);
CREATE INDEX idx_challans_party_date ON delivery_challans (party_id, challan_date DESC);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id, occurred_at DESC);
