export const REPORTS = [
  { id: 'consolidated', name: 'Consolidated Sale Book', group: 'Books & registers', note: 'Invoice totals from posted sales and processed/posted sale returns. Invoice-level differences, including round-off and missing item detail, remain visible and are never assigned to invented products.' },
  { id: 'sales', name: 'Sale Book', group: 'Books & registers', note: 'Posted sales lines plus clearly marked invoice-level adjustments. Authoritative invoice totals are preserved. Item/company filters exclude values not allocated to those dimensions.' },
  { id: 'returns', name: 'Sale Return Book', group: 'Books & registers', note: 'Posted or processed sale returns are negative credits. Header-only returns retain their recorded total; unknown tax and item details are not inferred.' },
  { id: 'misc', name: 'Misc.Sale Report', group: 'Analysis', note: 'Proposed salesperson summary. The reference image does not reveal the original submenu. Salesperson is Unassigned when the database does not record it.' },
  { id: 'item-analysis', name: 'Item Sale Analysis', group: 'Analysis', note: 'Net sales less billed and free units at the current recorded batch/item cost. This is an indicative margin, not historical COGS. Missing costs or item details produce a blank margin, never a fabricated zero.' },
  { id: 'claims', name: 'Incentives/Claims', group: 'Schemes & adjustments', note: 'Explicit claim/incentive business documents only. No incentive is inferred from sales. An empty report means no eligible source records are present.' },
  { id: 'free', name: 'Free Issued Analysis', group: 'Schemes & adjustments', note: 'Free units on recorded sale/return lines, valued at current recorded batch/item cost. Returns reverse issued units and cost.' },
  { id: 'adjustments', name: 'S/R, Brk, Rep/###, Other', group: 'Schemes & adjustments', note: 'The source label is partly unreadable. This view lists sales returns, breakages, replacements and explicit other adjustments. Activity values are positive magnitudes, not accounting postings.' },
  { id: 'stock', name: 'Bank Statement (Stock Valuation)', group: 'Stock & dispatch', note: 'Signed stock movements through the To date, grouped by item batch and warehouse. Valued at the current recorded batch cost/purchase price or item purchase rate. Historical costs are unavailable. From date and party do not apply; this is not a bank-certified statement.' },
  { id: 'dispatch', name: 'Tpt./Order/Dispatch Document', group: 'Stock & dispatch', note: 'Sales orders and delivery challans with transport references. Purchase orders are excluded. Order and dispatch quantities are separate activities and are not totalled together.' },
  { id: 'collection', name: 'Sale/Amendment/Collection', group: 'Books & registers', note: 'Posted sale/return value, explicit informational amendments and receipt-voucher party credits appear in separate columns. Receipt allocations are deduplicated against their vouchers; legacy voucher documents are included only when no posted voucher matches. This is not an outstanding balance report.' },
  { id: 'discount', name: 'Discount Statement', group: 'Schemes & adjustments', note: 'Recorded sales discounts, with return reversals. Any header-to-line difference remains a labelled invoice adjustment. Unknown amounts stay blank.' },
  { id: 'monthly', name: 'Monthly Summaries', group: 'Analysis', note: 'Calendar-month sales and return credits, with net amounts, tax, round-off and recorded invoice value. Uses actual dates and values, without scaling estimates.' },
  { id: 'item', name: 'Item Wise Sale', group: 'Analysis', note: 'Grouped by stable item ID. Unallocated invoice values are shown separately; they have no invented quantity or manufacturer.' },
  { id: 'company', name: 'Company Wise Sale', group: 'Analysis', note: 'Grouped by manufacturer/company ID, with a separate Unallocated group for invoice values without item-level company information.' },
  { id: 'party', name: 'Party Wise Sale', group: 'Analysis', note: 'Grouped by party ID. Includes recorded invoice totals and return credits. Documents are counted by database identity, not potentially reused document numbers.' },
] as const
export type ReportId = typeof REPORTS[number]['id']
