import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { deleteErp, getErp, patchErp, postErp } from '../../lib/erpApi'
import { useUIStore } from '../../store/uiStore'

export type CrudField = { key:string; label:string; type?:'text'|'number'|'date'|'datetime-local'|'select'; required?:boolean; options?:string[]; readOnly?:boolean }

export default function CrudTablePage({title,description,resource,fields}:{title:string;description:string;resource:string;fields:CrudField[]}){
  const [rows,setRows]=useState<Record<string,any>[]>([])
  const [editing,setEditing]=useState<Record<string,any>|null>(null)
  const [open,setOpen]=useState(false)
  const [search,setSearch]=useState('')
  const [busy,setBusy]=useState(false)
  const showToast=useUIStore((s)=>s.showToast)
  const load=()=>getErp<Record<string,any>[]>(resource).then(setRows).catch((e)=>showToast(e.message))
  useEffect(()=>{void load()},[resource,showToast])
  const visible=useMemo(()=>rows.filter((row)=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),[rows,search])
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const body=Object.fromEntries(fields.filter((f)=>!f.readOnly).map((f)=>{const raw=String(form.get(f.key)??'');return [f.key,f.type==='number'?(raw===''?null:Number(raw)):raw]}));setBusy(true);try{if(editing)await patchErp(resource,String(editing.id),body);else await postErp(resource,body);await load();setOpen(false);setEditing(null);showToast(editing?'Record updated.':'Record created.')}catch(error){showToast(error instanceof Error?error.message:'Could not save record.')}finally{setBusy(false)}}
  const remove=async(row:Record<string,any>)=>{if(!window.confirm('Delete this record? Referenced or posted records may be protected.'))return;try{await deleteErp(resource,String(row.id));setRows((current)=>current.filter((item)=>item.id!==row.id));showToast('Record deleted.')}catch(error){showToast(error instanceof Error?error.message:'Could not delete record.')}}
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="flex items-center gap-2 rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-600"><Plus size={16}/>New record</button></div>
    <div className="relative max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={15}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search all fields…" className="w-full rounded-lg border border-input bg-background py-2 pl-9 pr-3 text-sm"/></div>
    <div className="glass-surface overflow-x-auto rounded-xl"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border bg-muted/40">{fields.slice(0,6).map((field)=><th key={field.key} className="px-4 py-3 text-left text-xs font-semibold uppercase text-muted-foreground">{field.label}</th>)}<th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{visible.map((row)=><tr key={String(row.id)} className="border-b border-border/70 hover:bg-muted/30">{fields.slice(0,6).map((field)=><td key={field.key} className="max-w-[240px] truncate px-4 py-3">{row[field.key]===null||row[field.key]===undefined?'—':String(row[field.key])}</td>)}<td className="px-4 py-3 text-right"><button onClick={()=>{setEditing(row);setOpen(true)}} className="rounded p-2 text-muted-foreground hover:bg-blue-500/10 hover:text-blue-500" aria-label="Edit"><Pencil size={14}/></button><button onClick={()=>remove(row)} className="rounded p-2 text-muted-foreground hover:bg-red-500/10 hover:text-red-500" aria-label="Delete"><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!visible.length&&<div className="p-8 text-center text-sm text-muted-foreground">No records found. Use “New record” to add the first one.</div>}</div>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><form onSubmit={save} className="glass-surface max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-semibold">{editing?'Edit record':'New record'}</h2><p className="text-sm text-muted-foreground">All editable database fields for this module.</p></div><button type="button" onClick={()=>{setOpen(false);setEditing(null)}} className="rounded p-1 text-muted-foreground hover:bg-muted"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2">{fields.filter((f)=>!f.readOnly).map((field)=><label key={field.key} className="grid gap-1 text-sm font-medium">{field.label}{field.type==='select'?<select name={field.key} required={field.required} defaultValue={editing?.[field.key]??field.options?.[0]??''} className="rounded-lg border border-input bg-background px-3 py-2 font-normal">{field.options?.map((option)=><option key={option} value={option}>{option}</option>)}</select>:<input name={field.key} type={field.type??'text'} required={field.required} step={field.type==='number'?'any':undefined} defaultValue={editing?.[field.key]??''} className="rounded-lg border border-input bg-background px-3 py-2 font-normal"/>}</label>)}</div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>{setOpen(false);setEditing(null)}} className="rounded-lg border border-input px-4 py-2 text-sm">Cancel</button><button disabled={busy} className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Save record'}</button></div></form></div>}
  </div>
}
